[project]
name = "curobo-test"
version = "0.1.0"
description = "ROS 2 Workspace with cuRobo"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch",
    "ninja",
    "nvidia-curobo",
    "numpy>=2.0.0",
    "pytest",
    "setuptools",
    "wheel",
    "catkin-pkg>=1.1.0",
    "empy==3.3.4",
    "lark>=1.3.1",
    "matplotlib>=3.10.8",
    "scipy>=1.15.3",
]

[tool.uv]
[tool.uv.extra-build-dependencies]
nvidia-curobo = ["torch", "setuptools", "wheel", "numpy"]

[tool.uv.sources]
nvidia-curobo = { path = "./external/curobo", editable = true }

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu121"
explicit = true

[tool.uv.sources.torch]
index = "pytorch"
