FROM osrf/ros:humble-desktop

# Εγκατάσταση επιπλέον εργαλείων
RUN apt-get update && apt-get install -y \
    python3-colcon-common-extensions \
    ros-humble-rmw-cyclonedds-cpp \
    nano \
    && rm -rf /var/lib/apt/lists/*

# Ρύθμιση Workspace
WORKDIR /workspace

# Αυτόματη εκτέλεση source του ROS2
RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc
# Σημείωση: Το /home/ros2_ws/ που είχες, εδώ το αλλάζουμε σε /workspace 
# για να συμβαδίζει με το volume του compose
RUN echo "if [ -f /workspace/install/setup.bash ]; then source /workspace/install/setup.bash; fi" >> ~/.bashrc
